### ISSUE TITLE
1.67 is broken

### ISSUE THREAD

**Issue by rllola** [conan-community/conan-boost#145] opened 2018-08-20 21:20 UTC
I cannot build boost 1.67 anymore.

Here the error message : 
```
boost/1.67.0@conan/stable: Calling build()
WARN: patches/python_base_prefix.patch: source file is different - tools/build/src/tools/python.jam
boost/1.67.0@conan/stable: 
boost/1.67.0@conan/stable: ERROR: Package '4376b868ff655be5f55e0f0d253a60d40cb9bf5a' build failed
boost/1.67.0@conan/stable: WARN: Build folder /Users/travis/.conan/data/boost/1.67.0/conan/stable/build/4376b868ff655be5f55e0f0d253a60d40cb9bf5a
ERROR: boost/1.67.0@conan/stable: Error in build() method, line 86
	tools.patch(base_path=os.path.join(self.build_folder, self.folder_name), patch_file='patches/python_base_prefix.patch', strip=1)
	ConanException: Failed to apply patch: patches/python_base_prefix.patch
```

**Comment by lasote** [comment] 2018-08-21 07:04
Thanks. I'll check asap.

**Comment by lasote** [comment] 2018-08-21 07:13
I can't reproduce the error. Everything is building OK at my machine and all the CI machines. 
I would need more info to investigate, operating system, python version, conan version...

**Comment by rllola** [comment] 2018-08-23 09:01
I have the error inside my vagrant and for my travis build : 
https://travis-ci.org/rllola/zeronet-torrent-plugin/jobs/418432116

Here my travis file : 
https://github.com/rllola/zeronet-torrent-plugin/blob/travis-osx/.travis.yml

**Comment by rllola** [comment] 2018-08-23 09:19
I have the same error for 1.68. I believe that I might miss some dependencies because on my computer I can build it.

**Comment by rllola** [comment] 2018-08-23 09:52
I found more information on my problem. It look like I am experiencing this issue : https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

And I can try and solve it by doing that : 
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2

Currently testing. Have you tested your build on python 2 ?

**Comment by lasote** [comment] 2018-08-23 11:35
But the patch error and the SSL are not related I think. Yes, I've tried with python 2.

**Comment by lasote** [comment] 2018-08-23 11:40
The SSL error is commonly caused by a too old OpenSSL installed in the system. In travis, for linux, we always use docker containers to have upgraded compilers, tools, ... and so on.

About the patch error, I don't have a clue what can be happening.

**Comment by rllola** [comment] 2018-08-23 16:37
I can confirm 1.66 works for me and it doesn't have the pyenv patch thingy.

**Comment by lasote** [comment] 2018-08-27 08:34
Now I've been able to reproduce it, thanks. The key was building python. Will report ASAP.

**Comment by lasote** [comment] 2018-08-27 14:38
I've pushed the fix, will take some time to update because the CI is pretty busy.

**Comment by lasote** [comment] 2018-08-28 08:04
It should be fixed now. Please report if it doesn't!

**Closed by lasote** 2018-08-28 08:04 UTC

**Comment by rllola** [comment] 2018-08-28 08:18
It worked ! Thank you.

https://travis-ci.org/rllola/zeronet-torrent-plugin/jobs/421452715
