### ISSUE TITLE
Invalid c++ standard used when building

### ISSUE THREAD

**Issue by krojew** [conan-community/conan-boost#149] opened 2018-08-29 12:02 UTC
Due to https://github.com/boostorg/system/issues/26 c++14 flag needs to be explicitly passed when building boost with clang.

**Comment by lasote** [comment] 2018-08-30 10:29
Which operating system? Android?

**Comment by krojew** [comment] 2018-08-30 12:09
All systems - it's a compiler issue, not a system one.

**Comment by krojew** [comment] 2018-08-31 12:40
In such cases you need to pass `cxxstd=14` to b2.

**Comment by lasote** [comment] 2018-09-06 09:56
But what are the consequences of not passing the flag? Because it builds correctly with clang: https://travis-ci.org/conan-community/conan-boost

**Comment by krojew** [comment] 2018-09-06 11:04
Without this change it's not possible to link against boost when using clang with c++ >= 14. If you take a look at the issue from upstream, there's a big discussion about it and breaking binary compatibility.

**Comment by krojew** [comment] 2018-09-06 14:29
Here the relevant discussion: http://boost.2283326.n4.nabble.com/ABI-issues-with-std-td4704156.html

**Comment by Quincunx271** [comment] 2018-09-08 04:42
I'm pretty sure this just bit me hard. The prebuilt package that was selected doesn't seem to be ABI compatible with the compilation flags I was using (`-std=c++17`). Rather than being a link-time failure, this was a runtime error

**Comment by krojew** [comment] 2018-09-18 09:34
Any update?

**Comment by theirix** [comment] 2018-09-24 11:01
Confirmed it too, this fails with apple-clang 10 and clang 10.
Minimal example: https://github.com/theirix/boost-system-cxxstd-test

**Comment by lasote** [comment] 2018-09-26 09:37
I've merged #152, the new packages will be available in some hours when the CI ends. Please report if any issue.

https://ci.appveyor.com/project/lasote/conan-boost-su63s
https://travis-ci.org/conan-community/conan-boost

**Comment by SSE4** [comment] 2018-10-23 15:35
This issue was moved to conan-community/community#77

**Closed by SSE4** 2018-10-23 15:35 UTC
Labels: look into
